# Generated by Django 3.0.4 on 2021-02-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload/')),
                ('keyword', models.CharField(max_length=1000, verbose_name='Seprate each keywrod with comma (,) ')),
                ('web_author', models.CharField(max_length=50)),
                ('robot_tag', models.CharField(choices=[('noindex , nofollow', 'noindex , nofollow'), ('index, follow', 'index, follow')], default='noindex , nofollow', max_length=20)),
                ('google_bot', models.CharField(choices=[('noindex , nofollow', 'noindex , nofollow'), ('index, follow', 'index, follow')], default='noindex , nofollow', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Web_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('hero_image', models.ImageField(upload_to='upload/')),
                ('category_image', models.ImageField(upload_to='upload/')),
                ('sub_category_image', models.ImageField(upload_to='upload/')),
                ('comment_image', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
