# Generated by Django 3.0.4 on 2021-02-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_web_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('hero_image', models.ImageField(upload_to='upload/')),
                ('category_image', models.ImageField(upload_to='upload/')),
                ('sub_category_image', models.ImageField(upload_to='upload/')),
                ('comment_image', models.ImageField(upload_to='upload/')),
                ('facebook_link', models.CharField(max_length=200)),
                ('instagram_link', models.CharField(max_length=200)),
                ('twitter_link', models.CharField(max_length=200)),
                ('telegram_link', models.CharField(max_length=200)),
            ],
        ),
    ]
